import { StyleSheet } from '@react-pdf/renderer';

export const palette = {
  cobalt: '#2440C7',
  ink: '#15171C',
  ink2: '#565A63',
  ink3: '#8E929A',
  line: '#E4E4DD',
} as const;

export const styles = StyleSheet.create({
  page: {
    fontFamily: 'IBM Plex Sans',
    fontSize: 9.5,
    color: palette.ink,
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 44,
    lineHeight: 1.45,
  },
  header: {
    marginBottom: 6,
  },
  name: {
    fontFamily: 'Space Grotesk',
    fontSize: 22,
    fontWeight: 600,
    letterSpacing: -0.4,
    color: palette.ink,
  },
  titleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 4,
  },
  subtitle: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 9,
    color: palette.ink2,
    fontWeight: 500,
    letterSpacing: 0.3,
  },
  contactRow: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 6,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: palette.cobalt,
  },
  contactItem: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 8,
    color: palette.ink2,
  },
  contactLink: {
    color: palette.cobalt,
    textDecoration: 'none',
  },
  sectionTitle: {
    fontFamily: 'Space Grotesk',
    fontSize: 12,
    fontWeight: 600,
    color: palette.ink,
    letterSpacing: -0.2,
    marginTop: 16,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 0.5,
    borderBottomColor: palette.line,
  },
  summary: {
    fontSize: 9.5,
    color: palette.ink2,
    lineHeight: 1.5,
    marginTop: 12,
    marginBottom: 4,
  },
  skillGroup: {
    flexDirection: 'row',
    marginBottom: 4,
    alignItems: 'flex-start',
  },
  skillLabel: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 8,
    fontWeight: 500,
    color: palette.cobalt,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    width: 90,
    paddingTop: 1,
  },
  skillTags: {
    flex: 1,
    fontSize: 9,
    color: palette.ink,
  },
  project: {
    marginBottom: 10,
  },
  projHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'baseline',
  },
  projTitle: {
    fontFamily: 'Space Grotesk',
    fontSize: 11,
    fontWeight: 600,
    color: palette.ink,
  },
  projDomain: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 7.5,
    color: palette.ink3,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  projMeta: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 2,
  },
  projMetaItem: {
    flexDirection: 'row',
    gap: 3,
  },
  projMetaLabel: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 7.5,
    color: palette.ink3,
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  projMetaValue: {
    fontSize: 8.5,
    color: palette.ink2,
    fontWeight: 500,
  },
  projDesc: {
    fontSize: 9,
    color: palette.ink2,
    marginTop: 4,
    lineHeight: 1.45,
  },
  projImpact: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 4,
  },
  impactTag: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 7.5,
    color: palette.cobalt,
    backgroundColor: '#F0F2FF',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
  },
  projStack: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 7.5,
    color: palette.ink3,
    marginTop: 4,
  },
  ossItem: {
    fontSize: 8.5,
    color: palette.ink2,
    marginBottom: 3,
    lineHeight: 1.4,
  },
  ossName: {
    fontFamily: 'Space Grotesk',
    fontSize: 9,
    fontWeight: 600,
    color: palette.ink,
    textDecoration: 'none',
  },
  eduEntry: {
    marginBottom: 6,
  },
  eduYear: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 8,
    color: palette.cobalt,
    letterSpacing: 0.3,
  },
  eduDegree: {
    fontFamily: 'Space Grotesk',
    fontSize: 10,
    fontWeight: 600,
    color: palette.ink,
    marginTop: 1,
  },
  eduInst: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 8,
    color: palette.ink2,
    marginTop: 1,
  },
  certRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    marginTop: 6,
  },
  certTag: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 8,
    color: palette.ink2,
    backgroundColor: '#F2F2ED',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 3,
  },
  langRow: {
    flexDirection: 'row',
    gap: 20,
    flexWrap: 'wrap',
  },
  langItem: {
    flexDirection: 'row',
    gap: 4,
  },
  langName: {
    fontFamily: 'Space Grotesk',
    fontSize: 10,
    fontWeight: 600,
  },
  langLevel: {
    fontFamily: 'IBM Plex Mono',
    fontSize: 8,
    color: palette.ink2,
    paddingTop: 1.5,
  },
});
